name: bargainb
description: An Afdal Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.4.0+76

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  sign_in_with_apple: ^4.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  image_picker: ^0.8.6
  share_plus: ^6.0.0
  easy_localization: ^3.0.1
  flutter_automation: ^2.0.0
  google_sign_in: ^5.4.3
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dots_indicator: ^2.1.0
  http: ^0.13.5
  dotted_border: ^2.0.0+3
  flutter_branch_sdk: ^6.6.0
  flutter_contacts: ^1.1.6
  intl_phone_field: ^3.1.0
  pinput: ^2.2.31
  mixpanel_flutter: ^2.1.1
  app_tracking_transparency: ^2.0.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  infinite_scroll_pagination: ^3.2.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  country_picker: ^2.0.19
  shimmer_animation: 2.1.0+1
  showcaseview: ^2.0.3
  phone_number: ^1.0.0
  phone_form_field: ^7.0.5
  translator: ^0.1.7
  algolia_helper_flutter: ^0.3.3
  purchases_flutter: ^6.30.0
  syncfusion_flutter_charts: ^21.2.4
  table_calendar: ^3.0.8
  calendar_date_picker2: ^0.5.3
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  confetti: ^0.7.0
  easy_stepper: ^0.6.0
  audioplayers: ^4.1.0
  package_info_plus: ^3.1.2
  flutter_native_splash: ^2.2.19
  get_it: ^7.6.0
  sentry_flutter: ^8.1.0
  firebase_auth: ^5.1.2
  firebase_analytics: ^11.2.0
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  firebase_app_check: ^0.3.0+3
  firebase_messaging: ^15.0.3
  upgrader: ^6.5.0
  in_app_update: ^4.2.3
  flutter_typeahead: ^5.2.0




dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_android"
  ios: "launcher_ios"
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/icon/category_icons/
    - assets/icon/
    - assets/translations/
    - assets/sounds/


  fonts:
    - family: Paytone One
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

